language: python
python:
  - "3.8"

# command to install dependencies
install:
  - pip install git+https://github.com/morris-lab/CellOracle.git
# command to run tests
script:
  - ls # Test function will be added later.
